In [15]:
import pandas as pd
import json

In [16]:
df = pd.read_csv('scale_ai_parity_assessment_data_2022-08-17.csv')

In [17]:
df

,decision_date,product_id,source,catalog_id,srt_job_id,local_key,srt_answers,ds
0,8/17/22,3.238380e+15,scale.ai,3.228460e+14,4.723170e+14,3238380316274490.scale.ai.2022-08-16 11:50:03....,"[{""key"":""description"",""value"":[""match"",""match_...",8/17/22
1,8/17/22,4.074500e+15,scale.ai,5.167210e+14,1.126400e+15,4074497939324281.scale.ai.2022-08-16 11:50:03....,"[{""key"":""color"",""value"":[""no_match"",""no_match_...",8/17/22
2,8/17/22,5.075950e+15,scale.ai,2.970570e+14,7.592210e+14,5075946345806328.scale.ai.2022-08-16 11:50:03....,"[{""key"":""brand"",""value"":[""match"",""match_same"",...",8/17/22
3,8/17/22,7.674300e+15,scale.ai,3.383630e+14,1.074030e+15,7674301285943304.scale.ai.2022-08-16 11:50:03....,"[{""key"":""bag_closure"",""value"":[""match"",""match_...",8/17/22
4,8/17/22,4.690460e+15,scale.ai,1.724640e+15,1.112780e+15,4690462564367101.scale.ai.2022-08-17 11:03:46....,"[{""key"":""brand"",""value"":[""partial_match"",""part...",8/17/22
...,...,...,...,...,...,...,...,...
41868,8/17/22,5.849940e+15,scale.ai,1.176240e+15,5.973360e+14,5849942711701902.scale.ai.2022-08-16 11:50:03....,"[{""key"":""description"",""value"":[""match"",""match_...",8/17/22
41869,8/17/22,3.630990e+15,scale.ai,6.849940e+14,1.448460e+15,3630991426949895.scale.ai.2022-08-15 11:12:11....,"[{""key"":""description"",""value"":[""partial_match""...",8/17/22
41870,8/17/22,5.303310e+15,scale.ai,1.143830e+15,1.267040e+15,5303312539696422.scale.ai.2022-08-17 11:03:46....,"[{""key"":""brand"",""value"":[""no_match"",""no_match_...",8/17/22
41871,8/17/22,5.082960e+15,scale.ai,5.167210e+14,4.758240e+14,5082957595063695.scale.ai.2022-08-16 11:50:03....,"[{""key"":""brand"",""value"":[""match"",""match_same"",...",8/17/22
41872,8/17/22,4.738630e+15,scale.ai,2.724770e+14,1.326010e+15,4738629946168160.scale.ai.2022-08-16 11:50:03....,"[{""key"":""description"",""value"":[""match"",""match_...",8/17/22

In [18]:
dfparse ={}

for i in range(len(df)):
    try:
        df_x = json.loads(df['srt_answers'][i])
    except ValueError as e:
        print('Row',i, 'invalid json: %s' % e)

Row  31 invalid json: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)